spring.application.name=CafeSaaS Backend System

server.port = 8000

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.config.import=optional:classpath:application-secret.properties

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION_TIME}

application.security.jwt.refresh-token.expiration=86400000